### ISSUE TITLE
UT main generator: No support for custom package name

### ISSUE THREAD

**Issue by SKY-13th** [atilaneves/unit-threaded#111]
Hello. 

Stumbled on issue with generator.
As far as I understood, generator took in a count only 
file name, instead of `module` declaration inside of it.

As result, it is not possible to use custom 
name for a module or  use `package.d` file semantics.

#### File structure:

- src/
  - test_project/
     - foo.d => `module test_project.bar;`
     - pack_test/
        - package.d => `module test_project.pack_test;`

#### Generated Result:

``` D
import unit_threaded;

int main(string[] args)
{
    return args.runTests!(
                          "test_project.foo",
                          "test_project.pack_test.package",
                          );
}
```

#### Expected Result:

``` D
import unit_threaded;

int main(string[] args)
{
    return args.runTests!(
                          "test_project.bar",
                          "test_project.pack_test",
                          );
}
```

**Comment by atilaneves** [comment]
Thank you for your detailed issue report.

The generator is more of a convenience to make it easy for users to get started. This is indeed a bug, but I'm going to mark as it as "won't fix" because the workaround is to write the main file by hand. I actually just always do that now because of a dub bug that makes regenerating the main file too slow for me to handle.

Of course, if you care about this issue enough to submit a PR to fix it anyway, you're more than welcome.

**Comment by SKY-13th** [comment]
@atilaneves, ok, if I have a time will try to do something with it. =)

**Comment by atilaneves** [comment]
@SKY-13th Ok. If you do the PR, feel free to reopen this issue.
