### ISSUE TITLE
recommendation for a lib not using UT that depends no a lib that does use UT?

### ISSUE THREAD

**Issue by aliak00** [atilaneves/unit-threaded#128]
Hi, is there a way to handle this situation:

lib1 (depends on UT)
```
"configurations": [
        {
            "name": "unittest",
            "importPaths": [
                "./tests"
            ],
            "sourcePaths": [
                "./tests"
            ],
            "targetType": "executable",
            "preBuildCommands": ["dub run unit-threaded -c gen_ut_main -- -f bin/ut.d"],
            "mainSourceFile": "bin/ut.d",
            "dependencies": {
                "unit-threaded": "*"
            }
        },
```

lib2: (no UT)
```
"configurations": [
        {
            "name": "unittest",
            "sourcePaths": [
                "./algorithm/",
                "./functional/",
                "./utils/",
                "./range/"
            ]
        },
```
So lib2 basically has their own unittest config and when lib2 runs `dub test` you encounter:

"Error: module `unit_threaded` is in file 'unit_threaded.d' which cannot be read"

From inside `lib1/source.d` at this import point:

```
version(unittest) { import unit_threaded; }
else              { enum ShouldFail; }
```

Suggestions?

**Comment by atilaneves** [comment]
The way I handle it is like this:

lib1:

```json
"configurations":  [
    {
        "name": "unittest",
        "versions": ["testingLib1"]
    }
]
```

And instead of `version(unittest)` use `version(testingLib1)` to do the unit_threaded import.

But really, I recommend just [putting unit tests in their own source hierarchy](https://atilanevesoncode.wordpress.com/2018/03/22/keep-d-unittests-separated-from-production-code/) and avoiding problems like this altogether.
