### ISSUE TITLE
Stdout and stderr not output

### ISSUE THREAD

**Issue by russel** [atilaneves/unit-threaded#79]
Are stdout and stderr captured by unit-threaded and not output?

In investigating failures of tests, it is useful to be able to write stuff to stdout and stderr, but this appears not to appear on the console.

**Comment by atilaneves** [comment]
Yes, they're captured and on purpose, since by default tests run in parallel and the output would interleave. To get the output back, use the `-d` option. The function `writelnUt` is the recommended one for writing debug information in a test, otherwise you might have to also use the `-s` option to not get interleaved output when you use `-d`.

**Comment by russel** [comment]
I need to use writeln in the code under test not in the test itself, so I suspect I have to temporarily use -d, is it a compile-time or run time option?

**Comment by russel** [comment]
Answered own question, it's a run time option.
